Feature/issue 3
MoyeoRun/MoyeoRun_Back pull request #8
Opened 2021-09-28 04:09 UTC by InHyeok-J

## Main Development
- 개인런 시작(생성)
- 개인런 러닝 데이터 전송(달리는중)
- 개인런 러닝 종료(값 리턴)

## 작업사항

### 개인런 시작(생성)
- 개인런이 시작하면 jwt 토큰 안에 담겨져 있는 유저정보가 포함된 `running` 도큐먼트 생성,  프론트에서(3,2,1) 카운트 후 개인런 시작을 요청하면 카운트 하는동안 생성한 위치데이터의 평균을 넘겨주면서 시작 포인트가 지정됨,
### 개인런 러닝 데이터 전송(달리는중)
- 프론트가 위치 정보와 개인런 document의 id를 주면, 저장된 마지막 위치정보와 받아온 위치정보로 거리 계산후, 현재 러닝뛴 거리, 현재 평균 페이스, 위치 데이터의 전체 값을 프론트에게 넘겨줌. `common/utils`라는 폴더를 만들어서 두 위치정보간의 차이를 계산하는 함수 사용,

### 개인런 러닝 종료(값 리턴)
-  러닝이 종료 요청을 하면 총 러닝 시간을 계산해서 프론트에게 넘겨줌,

## 추가사항
### 몇가지 논의가 필요한 사항을 적어둡니다.
- 서비스 코드에 try catch를 통해 예외를 한번 발생시키도록 코드를 짰음. 
- 개인런과 관련한 예외처리(ex 중간에 네트워크 끊김)는 어떻게 처리 해야할까..
- running 이라는 도메인안에 single-running , multi-running 컨트롤러로 분리해서 처리 예정, 프로젝트 구조를 해치지는 않나?
- 테스트는 모여런study의 InHyeok 폴더 안에있는 서버로 `GET /single` 요청을 보내면 됨

Close #3

2021-10-01 13:28 UTC, DNATUNA requested changes
전체적으로 아주 스무스하구만.
생각보다 코드 양이 많지 않아서 살 맛 났다 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2021-10-01 13:28 UTC, DNATUNA commented on src/common/utils/dayUtil.ts
> +  console.log('현재시간', getKstTime());
테스트 해서 결과 잘 나오면 머지하기 전에 삭제해도 되겠다

2021-10-01 13:28 UTC, DNATUNA commented on src/common/utils/dayUtil.ts
> +  console.log('현재시간', getKstTime());
Nest.js는 파일의 name convention은 카멜 케이스로 안하는 것 같아
day.util.ts 어때?

2021-10-01 13:28 UTC, DNATUNA commented on src/common/utils/getDistance.ts
> +export const getDistance = (
함수 이름이 getDistance니까 파일 이름은 다른 걸로 짓는게 어때?
distance.util.ts는 어때?

2021-10-01 13:28 UTC, DNATUNA commented on src/running/controllers/single-running.controller.ts
> +  @UseGuards(JwtAuthGuard)
JwtAuthGuard가 JwtAccessAuthGuard로 바뀌어서 내가 머지할 때 직접 수정할게

2021-10-01 13:28 UTC, DNATUNA commented on src/running/dto/running.dto.ts
> +export class RunningDataDto {
DTO 네이밍에 `Dto` 빼는게 좋아보여
특히 아래에 있는 RunningRequestDto는 바꿔야 될 것 같아
~Request / ~Response가 이미 DTO라는 의미를 갖고 있어서 안써주는게 좋아

참고: [stackoverflow](https://stackoverflow.com/a/35341664)

다른 DTO들도 비슷한 맥락으로 수정해주면 좋아

2021-10-01 13:28 UTC, DNATUNA commented on src/running/dto/single-running.dto.ts
> +] as const) {}
API 문서 Swagger로 정할거면 이 코드 살려두고 아니면 기존 DTO로 변경하는게 좋아보여

2021-10-01 13:28 UTC, DNATUNA commented on src/running/schemas/running.schema.ts
> +_RunningSchema.virtual('responseData').get(function (this: Runnings) {
앞에 _ 붙이는게 mongoose 네이밍이야? 오지게 신기하네

2021-10-01 13:28 UTC, DNATUNA commented on src/running/schemas/running.schema.ts
> +export const RunningSchema = _RunningSchema;
export는 이렇게 하네 ㅋㅋㅋㅋㅋㅋㅋ뭐야 이거

2021-10-01 13:28 UTC, DNATUNA commented on src/running/services/single-running.service.ts
> +      });
이 친구들도 distance.util.ts로 빼면 코드 가독성 좋아질거야. 슥 빼버리자.

2021-10-01 13:28 UTC, DNATUNA commented on src/running/services/single-running.service.ts
> +        body.longitude,
지금 보니까 이 부분들도 중복되는거 봐서 DTO로 빼는게 어떨까 싶어

2021-10-01 13:30 UTC, InHyeok-J commented on src/running/schemas/running.schema.ts
> +_RunningSchema.virtual('responseData').get(function (this: Runnings) {
_언더바로 붙는게 내부적으로 접근하는? 네이밍을 짓더라고 ㅋㅋ _id같은 근데 몽구스 2주차라 ㅋㅋ

2021-10-03 11:45 UTC, InHyeok-J commented on src/running/services/single-running.service.ts
> +      });
저거 저번에 import 해오면 안되는 issue가 있었는데 한번 바꿔보고 되면 바꿀게

2021-10-05 01:07 UTC, InHyeok-J commented on src/common/utils/dayUtil.ts
> +  console.log('현재시간', getKstTime());
변경완료.

2021-10-05 01:07 UTC, InHyeok-J commented on src/running/controllers/single-running.controller.ts
> +  @UseGuards(JwtAuthGuard)
파이팅

2021-10-05 01:09 UTC, InHyeok-J commented on src/running/services/single-running.service.ts
> +        body.longitude,
dto로 빼도 어쩌피 서비스 코드에는 저렇게 적어줘야하지않나?

2021-10-05 09:52 UTC, InHyeok-J commented
@DNATUNA  수정했는데 한번 봐주세요~~

2021-10-06 14:47 UTC, DNATUNA approved these changes

2021-10-06 14:47 UTC, DNATUNA commented on src/running/dto/running.dto.ts
> +  longitude: number;
```suggestion
import { IsArray, IsNumber, IsString } from 'class-validator';

export type runData = {
  @IsNumber()
  latitude: number;

  @IsNumber()
  longitude: number;
```
여기에는 이렇게 IsNumber 안달아줘도 되나?
Suggest 기능이 있길래 한 번 써봤음 ㅋㅋㅋㅋㅋㅋ

2021-10-07 12:50 UTC, merged